services:
  postgres_auth:
    image: postgres:latest
    domainname: postgres_clever
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clever